server:
  port: 8080

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true

    # 1. Секретний ключ для JWT (вимога ТЗ)
jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLWxvbmctYW5kLXNlY3VyZS1zZWNyZXQta2V5LWZvci10aGUtand0LWdcnvY2V1cmU=}

service:
  # 2. URL для Service B (внутрішня Docker-адреса)
  data-api-url: ${DATA_API_URL:http://data-api:8081}

  # 3. Спільний секретний ключ для виклику Service B
  internal-token: ${INTERNAL_TOKEN:very_secret_internal_token}